export const signUp:string = "https://gallery-back.onrender.com/api/users/signup"
export const sigIn: string = "https://gallery-back.onrender.com/api/users/sigin"
export const getuserOne: string = "https://gallery-back.onrender.com/api/users/user/"
export const uploadInfo: string = "https://gallery-back.onrender.com/api/gallery/upload"
export const getAllImg: string = "https://gallery-back.onrender.com/api/gallery/allImages"
export const deleteImg: string = "https://gallery-back.onrender.com/api/gallery/allImages"
export const uploadImgUser: string = "https://gallery-back.onrender.com/api/users/user/upload"

// export const signUp:string = "http://localhost:4000/api/users/signup"
// export const sigIn: string = "http://localhost:4000/api/users/sigin"
// export const getuserOne: string = "http://localhost:4000/api/users/user/"
// export const uploadInfo: string = "http://localhost:4000/api/gallery/upload"
// export const getAllImg: string = "http://localhost:4000/api/gallery/allImages"
// export const deleteImg: string = "http://localhost:4000/api/gallery/allImages"
// export const uploadImgUser: string = "http://localhost:4000/api/users/user/upload"
